### ISSUE TITLE
source missing license header

### ISSUE THREAD

**Issue by KelseyBlodgett** [coolaj86/unibabel-js#5]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the Apache 2.0 License
Thanks.

**Comment by krolaw** [comment]
There's a license file in the same folder.  Why the need to be at the top of each file?

**Comment by coolaj86** [comment]
This isn't something that I care about. If you work at some company that requires it to be that way and you want to pull request it, I'll merge it in.
