### ISSUE TITLE
Unibabel.bufferToBase64 seems not to be working.

### ISSUE THREAD

**Issue by cganterh** [coolaj86/unibabel-js#6]
This is an interactive consloe session in Firefox 42.0:

```javascript
fr.readAsArrayBuffer(file_input.files[0])
undefined

fr.result
ArrayBuffer { byteLength: 585 }

Unibabel.bufferToBase64(fr.result)
""
```

**Comment by coolaj86** [comment]
It may be that you have to convert from ArrayBuffer to TypedArray first.

```javascript
var arr = new Uint8Array(fr.result);
Unibabel.bufferToBase64(arr);
```

I don't handle native binary conversions in the library on purpose - just Arrays and TypedArrays (because they have similar enough APIs to not require special code).

**Comment by cganterh** [comment]
Thank you very much! I just assumed I could use an ArrayBuffer directly.

**Comment by coolaj86** [comment]
Yeah... the Browser APIs are... weird...
